all:
#	g++ -c assembler.cpp  -o  ../object/assembler.o
#	g++ -c read_write.cpp -o  ../object/read_write.o
#	g++ -c cpu.cpp        -o  ../object/cpu.o
#	g++ -c stack.cpp      -o  ../object/stack.o
#	g++ -c make.cpp       -o  ../object/make.o
#	g++ -c make2.cpp      -o  ../object/make2.o
#	g++ -c assembler2.cpp -o  ../object/assembler2.o
#	g++ -c tag.cpp        -o  ../object/tag.o

#	g++ ../object/make.o   -o  ../EXE/make
#	g++ ../object/make2.o  -o  ../EXE/make2
#	g++ ../object/assembler.o  ../object/read_write.o -o ../EXE/Asm
#	g++ cpu.cpp        read_write.cpp stack.cpp -o ../EXE/CPU -lsfml-graphics -lsfml-window -lsfml-system
	g++ generate.cpp                                          -lsfml-graphics -lsfml-window -lsfml-system
#	g++ badapple.cpp									      -lsfml-graphics -lsfml-window -lsfml-system
#	g++ assembler2.cpp read_write.cpp tag.cpp   -o ../EXE/Asm2